spring:
  application:
    name: microservices-app
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

server:
  port: 8080

grpc:
  server:
    port: 9090

